"""Core framework components."""

from ai_automation_framework.core.config import Config, get_config
from ai_automation_framework.core.settings import Settings, get_settings
from ai_automation_framework.core.logger import get_logger
from ai_automation_framework.core.base import BaseComponent, Message, Response
from ai_automation_framework.core.usage_tracker import UsageTracker, get_usage_tracker
from ai_automation_framework.core.cache import ResponseCache, get_cache
from ai_automation_framework.core.exceptions import (
    AIAutomationError,
    LLMError,
    AuthenticationError,
    RateLimitError,
    NetworkError,
    APIError,
    ToolError,
    ConfigError,
    TimeoutError,
    ResourceError,
    RetryStrategy,
    RetryConfig,
    retry,
    create_error_context,
    wrap_exception,
)
from ai_automation_framework.core.async_utils import (
    run_sync,
    run_async,
    gather_with_concurrency,
    async_timeout,
    retry_async,
    AsyncLock,
)
from ai_automation_framework.core.sanitization import (
    sanitize_sql_identifier,
    sanitize_html,
    sanitize_path,
    sanitize_url,
    sanitize_email,
    escape_special_chars,
    validate_and_sanitize_input,
    sanitize_dict,
)
from ai_automation_framework.core.health import HealthCheck, HealthCheckResult, get_health_check
from ai_automation_framework.core.utils import (
    retry,
    async_retry,
    timeout,
    RateLimiter,
    chunk_list,
    safe_json_loads,
    truncate_string,
    format_bytes,
    merge_dicts,
)
from ai_automation_framework.core.circuit_breaker import (
    CircuitState,
    CircuitBreakerError,
    CircuitBreakerStats,
    CircuitBreaker,
    CircuitBreakerRegistry,
    get_registry,
    get_breaker,
    circuit_breaker,
)
from ai_automation_framework.core.metrics import (
    Counter,
    Gauge,
    Histogram,
    MetricsRegistry,
    MetricSnapshot,
    get_metrics_registry,
    counter,
    gauge,
    histogram,
    timed,
)
from ai_automation_framework.core.validation import (
    ValidationError,
    ValidatorBase,
    Required,
    TypeValidator,
    Range,
    Length,
    Pattern,
    Email,
    URL,
    Custom,
    And,
    Or,
    Not,
    Schema,
    PydanticValidator,
    validate_args,
    validate,
    validate_async,
)
from ai_automation_framework.core.middleware import (
    MiddlewareContext,
    Middleware,
    ConditionalMiddleware,
    LoggingMiddleware,
    TimingMiddleware,
    RetryMiddleware,
    CacheMiddleware,
    RateLimitMiddleware,
    MiddlewareStack,
    middleware_decorator,
)
from ai_automation_framework.core.di import (
    Container,
    Lifetime,
    LazyProxy,
    DIError,
    ResolutionError,
    CircularDependencyError,
    RegistrationError,
    get_global_container,
    reset_global_container,
)
from ai_automation_framework.core.tool_registry import (
    BaseTool,
    ToolMetadata,
    ToolRegistry,
    get_tool_registry,
    register_tool,
)
from ai_automation_framework.core.tool_interface import (
    ToolInterface,
    ToolResult,
)
from ai_automation_framework.core.security import (
    SecureConfig,
    SecureHTTPClient,
    SecureConfigError,
    APIKeyValidationError,
    require_api_key,
    sanitize_error_message,
)
from ai_automation_framework.core.result import (
    Result,
    ResultStatus,
    PaginatedResult,
)
from ai_automation_framework.core.token_budget import (
    TokenBudgetManager,
    BudgetConfig,
    BudgetPeriod,
    BudgetExceededError,
    TokenUsage,
    UsageStats,
    BaseUsageStore,
    SQLiteUsageStore,
    InMemoryUsageStore,
    get_budget_manager,
    calculate_cost,
)

__all__ = [
    "Config",
    "get_config",
    "Settings",
    "get_settings",
    "get_logger",
    "BaseComponent",
    "Message",
    "Response",
    "UsageTracker",
    "get_usage_tracker",
    "ResponseCache",
    "get_cache",
    # Exceptions
    "AIAutomationError",
    "LLMError",
    "AuthenticationError",
    "RateLimitError",
    "NetworkError",
    "APIError",
    "ToolError",
    "ConfigError",
    "TimeoutError",
    "ResourceError",
    "RetryStrategy",
    "RetryConfig",
    "retry",
    "create_error_context",
    "wrap_exception",
    "run_sync",
    "run_async",
    "gather_with_concurrency",
    "async_timeout",
    "retry_async",
    "AsyncLock",
    "sanitize_sql_identifier",
    "sanitize_html",
    "sanitize_path",
    "sanitize_url",
    "sanitize_email",
    "escape_special_chars",
    "validate_and_sanitize_input",
    "sanitize_dict",
    "HealthCheck",
    "HealthCheckResult",
    "get_health_check",
    "retry",
    "async_retry",
    "timeout",
    "RateLimiter",
    "chunk_list",
    "safe_json_loads",
    "truncate_string",
    "format_bytes",
    "merge_dicts",
    "CircuitState",
    "CircuitBreakerError",
    "CircuitBreakerStats",
    "CircuitBreaker",
    "CircuitBreakerRegistry",
    "get_registry",
    "get_breaker",
    "circuit_breaker",
    "Counter",
    "Gauge",
    "Histogram",
    "MetricsRegistry",
    "MetricSnapshot",
    "get_metrics_registry",
    "counter",
    "gauge",
    "histogram",
    "timed",
    "ValidationError",
    "ValidatorBase",
    "Required",
    "TypeValidator",
    "Range",
    "Length",
    "Pattern",
    "Email",
    "URL",
    "Custom",
    "And",
    "Or",
    "Not",
    "Schema",
    "PydanticValidator",
    "validate_args",
    "validate",
    "validate_async",
    "MiddlewareContext",
    "Middleware",
    "ConditionalMiddleware",
    "LoggingMiddleware",
    "TimingMiddleware",
    "RetryMiddleware",
    "CacheMiddleware",
    "RateLimitMiddleware",
    "MiddlewareStack",
    "middleware_decorator",
    "Container",
    "Lifetime",
    "LazyProxy",
    "DIError",
    "ResolutionError",
    "CircularDependencyError",
    "RegistrationError",
    "get_global_container",
    "reset_global_container",
    # Tool Registry
    "BaseTool",
    "ToolMetadata",
    "ToolRegistry",
    "get_tool_registry",
    "register_tool",
    # Tool Interface
    "ToolInterface",
    "ToolResult",
    # Security
    "SecureConfig",
    "SecureHTTPClient",
    "SecureConfigError",
    "APIKeyValidationError",
    "require_api_key",
    "sanitize_error_message",
    # Result Types
    "Result",
    "ResultStatus",
    "PaginatedResult",
    # Token Budget Management
    "TokenBudgetManager",
    "BudgetConfig",
    "BudgetPeriod",
    "BudgetExceededError",
    "TokenUsage",
    "UsageStats",
    "BaseUsageStore",
    "SQLiteUsageStore",
    "InMemoryUsageStore",
    "get_budget_manager",
    "calculate_cost",
]
